### ISSUE TITLE
Problem with angular

### ISSUE THREAD

**Issue by enyo** [a14n/dart-google-maps#37]
This problem seems to be closely related to a14n/dart-js-wrapping#8 since the errors are the same.

When including `google_maps` and `angular2` in the same library, there are many errors like these:

```
[Error from Dart2JS on angular_maps|web/index.dart]:
packages/google_maps/src/core/mvc/mvcobject.dart:19:3:
External method without an implementation.
  external factory _MVCObject();
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I have created a very [simple test project](https://github.com/enyo/google_maps_angular) to see it in action:

```bash
mkdir /tmp/google_maps_angular &&
cd /tmp/google_maps_angular &&
git clone https://github.com/enyo/google_maps_angular.git . &&
pub get &&
pub build
```

**NOTE**: the test project uses this dependency override, as suggested in a14n/dart-js-wrapping#8:

```yaml
# Full pubspec.yaml:
name: angular_maps
dependencies:
  google_maps: ^3.1.0
  angular2: "2.0.0-beta.22"
dependency_overrides:
  source_gen: "^0.5.0"
```

Any suggestions on how to fix this issue are greatly appreciated!

**Comment by enyo** [comment]
PS: last time, I found that my project included the `dart:io` library by mistake, do you think that this could be the case for angular as well?

**Comment by a14n** [comment]
Not an expert of angular2 (for now) but it looks like you have to use the `angular2` transformer to get ride of those errors : 

```yaml
name: angular_maps
dependencies:
  google_maps: ^3.1.0
  angular2: "2.0.0-beta.22"
dependency_overrides:
  source_gen: "^0.5.0"
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/index.dart
```

Let me know if that works.
